# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synonym',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='synonym',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='synonym',
            name='type',
            field=models.CharField(choices=[('I', 'Index Time'), ('Q', 'Query Time'), ('C', 'Category'), ('S', 'Suggest')], default='Q', max_length=50),
        ),
        migrations.AddField(
            model_name='synonym',
            name='user_added',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='synonym',
            name='user_last_modified',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='lhs',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='rhs',
            field=models.CharField(max_length=100),
        ),
    ]
