# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170116_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synonym',
            name='user_added',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='user_last_modified',
            field=models.CharField(default='Admin', max_length=100),
        ),
    ]
