# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170215_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Synonym',
        ),
    ]
