# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-15 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170415_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='Midfielder', max_length=100),
            preserve_default=False,
        ),
    ]
