# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-15 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=['G', 'o', 'a', 'l', 'K', 'e', 'e', 'p', 'e', 'r'], max_length=100),
        ),
    ]
