# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170417_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='shirt_number',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
